language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
  - pip install --user cpp-coveralls
install:
  - sudo apt-get -qq install autoconf automake autotools-dev libtool pkg-config libssl-dev tcl-dev libexpat1-dev libpcre3-dev libmodule-install-perl
  - sudo apt-get -qq install ruby
before_script:
  - echo '-------------------------------'
  - echo 'Build and install TrafficServer'
  - echo '-------------------------------'
  - wget -O trafficserver-6.1.1.tar.gz https://github.com/apache/trafficserver/archive/6.1.1.tar.gz
  - tar xf trafficserver-6.1.1.tar.gz
  - cd trafficserver-6.1.1
  - autoreconf -if
  - ./configure --enable-cppapi --disable-tests
  - make -j2
  - sudo make install
  - sudo cp lib/ink_autoconf.h /usr/local/include/ # ugly hack! related to TS-2794, TS-3427 ...
  - cd ../
script:
  - autoreconf -if
  - ./configure --enable-coverage --with-ts-prefix-root=/usr/local/
  - echo '-------------------------------'
  - echo 'Build mruby'
  - echo '-------------------------------'
  - CFLAGS="-fPIC" make build_mruby
  - echo '-------------------------------'
  - echo 'Build ts_mruby'
  - echo '-------------------------------'
  - make
  - sudo make install
  - echo '-------------------------------'
  - echo 'Run unit test'
  - echo '-------------------------------'
  - make test 2> /dev/null
  - echo '-------------------------------'
  - echo 'Run functional test'
  - echo '-------------------------------'
  - sudo ldconfig
  - sudo chmod 777 -R /usr/local/etc/trafficserver/
  - sudo chmod 777 -R /usr/local/var/trafficserver/
  - sudo chmod 777 -R /usr/local/var/log/
  - ATS_PREFIX=/usr/local/ sh ./t.sh
after_success:
  - coveralls -i src/ -b test/ -E '.*\/libs\/.*' -E '.*\/include\/.*' -E '.*\/googletest\/.*' --gcov-options '\-lp'
