language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
  - pip install --user cpp-coveralls
install:
  - sudo apt-get -qq install autoconf automake autotools-dev libtool pkg-config libssl-dev tcl-dev libexpat1-dev libpcre3-dev libmodule-install-perl
  - sudo apt-get -qq install ruby
before_script:
  - echo '-------------------------------'
  - echo 'Build and install TrafficServer'
  - echo '-------------------------------'
  - wget -O trafficserver-7.0.0.tar.bz2 http://ftp.jaist.ac.jp/pub/apache/trafficserver/trafficserver-7.0.0.tar.bz2
  - tar xf trafficserver-7.0.0.tar.bz2
  - cd trafficserver-7.0.0
  - autoreconf -if
  - ./configure --disable-tests
  - make -j2
  - sudo make install
  - cd ../
script:
  - autoreconf -if
  - ./configure --enable-coverage --with-ts-prefix-root=/usr/local/
  - echo '-------------------------------'
  - echo 'Build mruby'
  - echo '-------------------------------'
  - CFLAGS="-fPIC" make build_mruby
  - echo '-------------------------------'
  - echo 'Build ts_mruby'
  - echo '-------------------------------'
  - make
  - sudo make install
  - echo '-------------------------------'
  - echo 'Run unit test'
  - echo '-------------------------------'
  - make test 2> /dev/null
  - echo '-------------------------------'
  - echo 'Run functional test'
  - echo '-------------------------------'
  - sudo ldconfig
  - sudo chmod 777 -R /usr/local/etc/trafficserver/
  - sudo chmod 777 -R /usr/local/var/trafficserver/
  - sudo chmod 777 -R /usr/local/var/log/
  - ATS_PREFIX=/usr/local/ sh ./t.sh
after_success:
  - coveralls -i src/ -b test/ -E '.*\/libs\/.*' -E '.*\/include\/.*' -E '.*\/googletest\/.*' --gcov-options '\-lp'
