/*
// ts_mruby_config_keys.hpp - constants related to TSOverridableConfigKey
//
// TODO automatically generate from apidefs.h to follow ATS core update
//
*/

#ifndef TS_MRUBY_CONFIG_KEYS_H
#define TS_MRUBY_CONFIG_KEYS_H

#include <ts/apidefs.h>

/*
 * string representation of 'TSOverridableConfigKey' enum type
 *
 * NOTE: These entries are based on lib/ts/apidefs.h.in on trafficserver.
 * so, we must follow updates of trafficserver core...
 */
const static char* OVERRIDABLE_CONFIG_KEY[] = {
  // "TS_CONFIG_NULL" is -1, invalid and unnecessary index
  "TS_CONFIG_URL_REMAP_PRISTINE_HOST_HDR",
  "TS_CONFIG_HTTP_CHUNKING_ENABLED",
  "TS_CONFIG_HTTP_NEGATIVE_CACHING_ENABLED",
  "TS_CONFIG_HTTP_NEGATIVE_CACHING_LIFETIME",
  "TS_CONFIG_HTTP_CACHE_WHEN_TO_REVALIDATE",
  "TS_CONFIG_HTTP_KEEP_ALIVE_ENABLED_IN",
  "TS_CONFIG_HTTP_KEEP_ALIVE_ENABLED_OUT",
  "TS_CONFIG_HTTP_KEEP_ALIVE_POST_OUT",
  "TS_CONFIG_HTTP_SERVER_SESSION_SHARING_MATCH",
  "TS_CONFIG_NET_SOCK_RECV_BUFFER_SIZE_OUT",
  "TS_CONFIG_NET_SOCK_SEND_BUFFER_SIZE_OUT",
  "TS_CONFIG_NET_SOCK_OPTION_FLAG_OUT",
  "TS_CONFIG_HTTP_FORWARD_PROXY_AUTH_TO_PARENT",
  "TS_CONFIG_HTTP_ANONYMIZE_REMOVE_FROM",
  "TS_CONFIG_HTTP_ANONYMIZE_REMOVE_REFERER",
  "TS_CONFIG_HTTP_ANONYMIZE_REMOVE_USER_AGENT",
  "TS_CONFIG_HTTP_ANONYMIZE_REMOVE_COOKIE",
  "TS_CONFIG_HTTP_ANONYMIZE_REMOVE_CLIENT_IP",
  "TS_CONFIG_HTTP_ANONYMIZE_INSERT_CLIENT_IP",
  "TS_CONFIG_HTTP_RESPONSE_SERVER_ENABLED",
  "TS_CONFIG_HTTP_INSERT_SQUID_X_FORWARDED_FOR",
  "TS_CONFIG_HTTP_SERVER_TCP_INIT_CWND",
  "TS_CONFIG_HTTP_SEND_HTTP13_REQUESTS",
  "TS_CONFIG_HTTP_CACHE_HTTP",
  "TS_CONFIG_HTTP_CACHE_CLUSTER_CACHE_LOCAL",
  "TS_CONFIG_HTTP_CACHE_IGNORE_CLIENT_NO_CACHE",
  "TS_CONFIG_HTTP_CACHE_IGNORE_CLIENT_CC_MAX_AGE",
  "TS_CONFIG_HTTP_CACHE_IMS_ON_CLIENT_NO_CACHE",
  "TS_CONFIG_HTTP_CACHE_IGNORE_SERVER_NO_CACHE",
  "TS_CONFIG_HTTP_CACHE_CACHE_RESPONSES_TO_COOKIES",
  "TS_CONFIG_HTTP_CACHE_IGNORE_AUTHENTICATION",
  "TS_CONFIG_HTTP_CACHE_CACHE_URLS_THAT_LOOK_DYNAMIC",
  "TS_CONFIG_HTTP_CACHE_REQUIRED_HEADERS",
  "TS_CONFIG_HTTP_INSERT_REQUEST_VIA_STR",
  "TS_CONFIG_HTTP_INSERT_RESPONSE_VIA_STR",
  "TS_CONFIG_HTTP_CACHE_HEURISTIC_MIN_LIFETIME",
  "TS_CONFIG_HTTP_CACHE_HEURISTIC_MAX_LIFETIME",
  "TS_CONFIG_HTTP_CACHE_GUARANTEED_MIN_LIFETIME",
  "TS_CONFIG_HTTP_CACHE_GUARANTEED_MAX_LIFETIME",
  "TS_CONFIG_HTTP_CACHE_MAX_STALE_AGE",
  "TS_CONFIG_HTTP_KEEP_ALIVE_NO_ACTIVITY_TIMEOUT_IN",
  "TS_CONFIG_HTTP_KEEP_ALIVE_NO_ACTIVITY_TIMEOUT_OUT",
  "TS_CONFIG_HTTP_TRANSACTION_NO_ACTIVITY_TIMEOUT_IN",
  "TS_CONFIG_HTTP_TRANSACTION_NO_ACTIVITY_TIMEOUT_OUT",
  "TS_CONFIG_HTTP_TRANSACTION_ACTIVE_TIMEOUT_OUT",
  "TS_CONFIG_HTTP_ORIGIN_MAX_CONNECTIONS",
  "TS_CONFIG_HTTP_CONNECT_ATTEMPTS_MAX_RETRIES",
  "TS_CONFIG_HTTP_CONNECT_ATTEMPTS_MAX_RETRIES_DEAD_SERVER",
  "TS_CONFIG_HTTP_CONNECT_ATTEMPTS_RR_RETRIES",
  "TS_CONFIG_HTTP_CONNECT_ATTEMPTS_TIMEOUT",
  "TS_CONFIG_HTTP_POST_CONNECT_ATTEMPTS_TIMEOUT",
  "TS_CONFIG_HTTP_DOWN_SERVER_CACHE_TIME",
  "TS_CONFIG_HTTP_DOWN_SERVER_ABORT_THRESHOLD",
  "TS_CONFIG_HTTP_CACHE_FUZZ_TIME",
  "TS_CONFIG_HTTP_CACHE_FUZZ_MIN_TIME",
  "TS_CONFIG_HTTP_DOC_IN_CACHE_SKIP_DNS",
  "TS_CONFIG_HTTP_BACKGROUND_FILL_ACTIVE_TIMEOUT",
  "TS_CONFIG_HTTP_RESPONSE_SERVER_STR",
  "TS_CONFIG_HTTP_CACHE_HEURISTIC_LM_FACTOR",
  "TS_CONFIG_HTTP_CACHE_FUZZ_PROBABILITY",
  "TS_CONFIG_HTTP_BACKGROUND_FILL_COMPLETED_THRESHOLD",
  "TS_CONFIG_NET_SOCK_PACKET_MARK_OUT",
  "TS_CONFIG_NET_SOCK_PACKET_TOS_OUT",
  "TS_CONFIG_HTTP_INSERT_AGE_IN_RESPONSE",
  "TS_CONFIG_HTTP_CHUNKING_SIZE",
  "TS_CONFIG_HTTP_FLOW_CONTROL_ENABLED",
  "TS_CONFIG_HTTP_FLOW_CONTROL_LOW_WATER_MARK",
  "TS_CONFIG_HTTP_FLOW_CONTROL_HIGH_WATER_MARK",
  "TS_CONFIG_HTTP_CACHE_RANGE_LOOKUP",
  "TS_CONFIG_HTTP_NORMALIZE_AE_GZIP",
  "TS_CONFIG_HTTP_DEFAULT_BUFFER_SIZE",
  "TS_CONFIG_HTTP_DEFAULT_BUFFER_WATER_MARK",
  "TS_CONFIG_HTTP_REQUEST_HEADER_MAX_SIZE",
  "TS_CONFIG_HTTP_RESPONSE_HEADER_MAX_SIZE",
  "TS_CONFIG_HTTP_NEGATIVE_REVALIDATING_ENABLED",
  "TS_CONFIG_HTTP_NEGATIVE_REVALIDATING_LIFETIME",
  "TS_CONFIG_HTTP_ACCEPT_ENCODING_FILTER_ENABLED",
  "TS_CONFIG_SSL_HSTS_MAX_AGE",
  "TS_CONFIG_SSL_HSTS_INCLUDE_SUBDOMAINS",
  "TS_CONFIG_HTTP_CACHE_OPEN_READ_RETRY_TIME",
  "TS_CONFIG_HTTP_CACHE_MAX_OPEN_READ_RETRIES",
  "TS_CONFIG_HTTP_CACHE_RANGE_WRITE",
  "TS_CONFIG_HTTP_POST_CHECK_CONTENT_LENGTH_ENABLED",
  "TS_CONFIG_HTTP_GLOBAL_USER_AGENT_HEADER",
  "TS_CONFIG_HTTP_AUTH_SERVER_SESSION_PRIVATE",
  "TS_CONFIG_HTTP_SLOW_LOG_THRESHOLD",
  "TS_CONFIG_HTTP_CACHE_GENERATION",
  "TS_CONFIG_BODY_FACTORY_TEMPLATE_BASE",
  "TS_CONFIG_HTTP_CACHE_OPEN_WRITE_FAIL_ACTION",
  "TS_CONFIG_HTTP_ENABLE_REDIRECTION",
  "TS_CONFIG_HTTP_NUMBER_OF_REDIRECTIONS",
  "TS_CONFIG_HTTP_CACHE_MAX_OPEN_WRITE_RETRIES",
  "TS_CONFIG_HTTP_REDIRECT_USE_ORIG_CACHE_KEY",
  "TS_CONFIG_HTTP_ATTACH_SERVER_SESSION_TO_CLIENT",
  "TS_CONFIG_HTTP_ORIGIN_MAX_CONNECTIONS_QUEUE",
  "TS_CONFIG_WEBSOCKET_NO_ACTIVITY_TIMEOUT",
  "TS_CONFIG_WEBSOCKET_ACTIVE_TIMEOUT",
  "TS_CONFIG_HTTP_UNCACHEABLE_REQUESTS_BYPASS_PARENT",
  "TS_CONFIG_HTTP_PARENT_PROXY_TOTAL_CONNECT_ATTEMPTS",
  "TS_CONFIG_HTTP_TRANSACTION_ACTIVE_TIMEOUT_IN",
  ""
};

#endif // TS_MRUBY_CONFIG_KEYS_H
